# The Project API Token from Web Translate It
api_key: 4af21ce1fb3a4f7127a60b31ebc41c1446b38bb2

# The Master locale is the locale you translate your project from. Web Translate It shouldn’t 
# attempt to edit these files.
ignore_locales: en_GB
